# Generated by Django 4.1 on 2023-10-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_display', '0002_element_description_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='count',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
