# Generated by Django 4.2.7 on 2023-12-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_display', '0005_remove_client_phone_number_alter_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(blank=True, default=669778334),
            preserve_default=False,
        ),
    ]
