# Generated by Django 4.2.7 on 2023-12-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_display', '0008_element_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='units',
            new_name='unit',
        ),
    ]
