# Generated by Django 4.2.7 on 2023-12-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_display', '0009_rename_units_element_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='total_volume',
            new_name='volume',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2),
        ),
    ]
