# Generated by Django 4.2.7 on 2023-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_display', '0010_rename_total_volume_element_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adres',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
