# Generated by Django 4.2.7 on 2023-12-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_display', '0012_order_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='status',
            field=models.CharField(choices=[('zrobione', 'Done'), ('do zrobienia', 'In Progress')], default='do zrobienia', max_length=12),
        ),
    ]
